language: ruby

# creates 3 variable build maxtix. 1 each for a different RVM version
rvm:
  - 2.0.0
  - 1.9.3
  - jruby-19mode

# add the extra shell commands to ensure the db exits, the 
# migrations have ben run, and the development env schema has
# been applied to the test database.
#
before_script:
  - rake db:create
  - rake db:migrate