# Database configuration
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000   
  username: annales_insa
  password: annales_insa
  database: annales-dev

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
  username: annales_insa
  password: annales_insa
  database: annales-test
